
genomes:
  hg38:
    url: "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.2bit"
  hg38_numeric:
    url: "local_data/hg38_numeric.2bit"
  hg38_small_test:
    url: "local_data/hg38_small_test.fa"
  sacCer3:
    url: "local_data/sacCer3.2bit"
  mm10:
    url: "local_data/mm10_numeric.fa"


# Note: There should also be a .tbi index file for each .vcf.gz file
variants:
  thousand_genomes:
    url: "data/variants.vcf.gz"
  thousand_genomes_small_test:
    url: "local_data/thousand_genomes_small_test.vcf.gz"
  sacCer3:
    url: "local_data/sacCer3.vcf.gz"
  sacCer3_common:
    url: "local_data/sacCer3_common.vcf.gz"
  mouse_genomes_project:
    url: "local_data/mgp_common.vcf.gz"


truth_datasets:
  hg002:
    vcf: "local_data/truth_hg002.vcf.gz"
    regions: "local_data/truth_hg002_regions.bed"

  yeast_BKI:
    vcf: "local_data/truth_BKI.vcf.gz"
    regions: "local_data/truth_BKI_regions.bed"


# k-mer size for kage, should not be larger than 31
k: 31

# n threads to use when making indexing data. Should be set to number of cores available
n_threads_data: 30

# smaller number of threads to used for memory-intensive tasks
n_threads_data_quarter: 20

# number of threads to use when sampling kmer counts from population
# memory use scales linearly with this
n_threads_population_sampling: 25

# number of threads for making kmer index. Should be set to number of cores available
n_threads_kmer_index: 40

# random seed for random operations, e.g. when using random individuals for the model
random_seed: 1


# Configuration for varius indexes
# Each index below should have a name starting with dataset and followed by a number (e.g. dataset1).
# The index will be built in a folder inside the data directory (e.g. data/dataset1).
# n_nodes should be a guess of the number of graph nodes requierd to build the genome graph
# n_nodes only needs to be larger than the actual number of nodes, i.e. set it to the number of variants x 4 to be safe

analysis_regions:
  # Example: Will build an index only for chromosome 1, basepairs 1 to 5m
  dataset1:
    reference: hg38_small_test  # this should point to the name of a reference genome specified above
    variants: thousand_genomes_small_test  # this should point to a set of variants specified above
    region: "1:1-5000000"
    genome_size: "5000000"
    chromosomes: "1"
    simulation_chromosomes: "1"
    n_nodes: "5000000"

  # Example: Whole genome index
  dataset2:
    reference: hg38_numeric
    variants: thousand_genomes
    region: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X"
    genome_size: "3031000000"
    chromosomes: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X"
    n_nodes: "84000000"  # enough for a vcf of approx 28 mill variants

  # Chromosome 1
  dataset3:
    reference: hg38_numeric
    variants: thousand_genomes
    region: "1"
    genome_size: "248956422"
    chromosomes: "1"
    n_nodes: "10000000"  # enough for a vcf of approx 28 mill variants

  dataset10:
    reference: sacCer3
    variants: sacCer3
    region: "chrIV chrV"
    chromosomes: "chrIV chrXV"
    genome_size: "2623224"

  yeast_small_test:
    reference: sacCer3
    variants: sacCer3_common
    region: "chrIV chrXV"
    simulation_chromosomes: "chrIV chrXV"
    chromosomes: "chrIV chrXV"
    genome_size: "2623224"

  yeast_whole_genome:
    reference: sacCer3
    variants: sacCer3_common
    region: 'chrI chrII chrIII chrIV chrV chrVI chrVII chrVIII chrIX chrX chrXI chrXII chrXIII chrXIV chrXV chrXVI'
    simulation_chromosomes: 'chrI chrII chrIII chrIV chrV chrVI chrVII chrVIII chrIX chrX chrXI chrXII chrXIII chrXIV chrXV chrXVI'
    chromosomes: 'chrI chrII chrIII chrIV chrV chrVI chrVII chrVIII chrIX chrX chrXI chrXII chrXIII chrXIV chrXV chrXVI'
    genome_size: 12071326

  mouse_small:
    reference: mm10
    variants: mouse_genomes_project
    genome_size: "61431566"
    region: "19"
    chromosomes: "19"
    simulation_chromosomes: "19"

  mouse_whole_genome:
    reference: mm10
    variants: mouse_genomes_project
    genome_size: "2633776672"
    region: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 X"
    chromosomes: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 X"
    simulation_chromosomes: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19"



max_variant_nodes: 3
use_kivs: False
kivs_kmer_index: False
kivs_minimize_overlaps: False
kivs_align_windows: False
