
# k-mer size for kage, should not be larger than 31
k:
  31

n_threads:
  16

# n threads to use when indexing data
n_threads_data:
  40

# smaller number of threads to used for memory-intensive tasks
n_threads_data_quarter:
  25

hg38_2bit_file:
  "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.2bit"
  #"http://ivarg.ddns.net/hg38.2bit"

random_seed:
  1

# Full list of chromosomes, space-separated
chromosomes:
  "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X"

# Path to genotyped variants that indexes will be based on
# Note: You will also need a vcf index file in the same location (e.g. variants.vcf.gz.tbi)
variants_file:
  "data/variants.vcf.gz"

reference_file:
  "data/reference.fa"


# Configuration for varius indexes
# Each index below should have a name starting with dataset and followed by a number (e.g. dataset1).
# The index will be built in a folder inside the data directory (e.g. data/dataset1).
# n_nodes should be a guess of the number of nodes requierd to build the genome graph
#   n_nodes only needs to be larger than the actual number of nodes, set to number of variants x 4 to be safe


analysis_regions:
  # Example: Will build an index only for chromosome 1, basepairs 1 to 5m
  dataset1:
    region: "1:1-5000000"
    genome_size: "5000000"
    chromosomes: "1"
    simulation_chromosomes: "1"
    n_nodes: "5000000"

  # Example: Whole genome index
  dataset2:
    region: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X"
    genome_size: "3031000000"
    chromosomes: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X"
    n_nodes: "84000000"  # enough for a vcf of approx 28 mill variants

