
genomes:
  hg38:
    url: "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.2bit"
  hg38_numeric:
    url: "local_data/hg38_numeric.2bit"
  hg38_small:
    url: "local_data/hg38_small_test.2bit"
  sacCer3:
    url: "local_data/sacCer3.2bit"


# Note: There should also be a .tbi index file for each .vcf.gz file
variants:
  thousand_genomes:
    url: "data/variants.vcf.gz"
  thousand_genomes_small_test:
    url: "local_data/thousand_genomes_small_test.vcf.gz"
  sacCer3:
    url: "local_data/sacCer3.vcf.gz"
  sacCer3_common:
    url: "local_data/sacCer3_common.vcf.gz"


# k-mer size for kage, should not be larger than 31
k: 31

# n threads to use when indexing data
n_threads_data: 40

# smaller number of threads to used for memory-intensive tasks
n_threads_data_quarter: 25


# Configuration for varius indexes
# Each index below should have a name starting with dataset and followed by a number (e.g. dataset1).
# The index will be built in a folder inside the data directory (e.g. data/dataset1).
# n_nodes should be a guess of the number of nodes requierd to build the genome graph
#   n_nodes only needs to be larger than the actual number of nodes, set to number of variants x 4 to be safe

analysis_regions:
  # Example: Will build an index only for chromosome 1, basepairs 1 to 5m
  dataset1:
    reference: hg38_small_test  # this should point to the name of a reference genome specified above
    variants: thousand_genomes_small_test  # this should point to a set of variants specified above
    region: "1:1-5000000"
    genome_size: "5000000"
    chromosomes: "1"
    simulation_chromosomes: "1"
    n_nodes: "5000000"

  # Example: Whole genome index
  dataset2:
    reference: hg38
    variants: thousand_genomes
    region: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X"
    genome_size: "3031000000"
    chromosomes: "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 X"
    n_nodes: "84000000"  # enough for a vcf of approx 28 mill variants

  dataset10:
    reference: sacCer3
    variants: sacCer3
    region: "chrIV chrV"
    chromosomes: "chrIV chrXV"
    genome_size: "2623224"

  dataset11:
    reference: sacCer3
    variants: sacCer3_common
    region: "chrIV chrXV"
    chromosomes: "chrIV chrXV"
    genome_size: "2623224"
