
name: Test

on:
  # small benchmark on push and pull request
  push:
    branches: ["dev", "master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Run test
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.'
          snakefile: 'Snakefile'
          args: '-F --cores 8 --config n_threads_data=2 --config n_threads_data_quarter=2 --config n_threads_population_sampling=1 --config n_threads_kmer_index=1 --use-conda data/dataset1/index_25all.npz'  # test building a small human index
          stagein: |
            apt-get update
            apt-get -y install gcc
            python -m pip install --upgrade pip setuptools wheel
            pip install -r python_requirements.txt


